language: en
pipeline:
- name: SpacyNLP
  model: en_core_web_lg
- name: SpacyTokenizer
- name: RegexFeaturizer
- name: RegexEntityExtractor
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 150
  random_seed: 1
- name: FallbackClassifier
  threshold: 0.85
- name: DucklingEntityExtractor
  url: http://duckling:8000
  dimensions:
  - email
- name: EntitySynonymMapper
policies:
- name: AugmentedMemoizationPolicy
  max_history: 4
- name: TEDPolicy
  max_history: 4
  epochs: 100
- name: RulePolicy
  core_fallback_threshold: 0.8
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
