API_KEY: "Zwh-e8Cm2znF7_wsKHhWffsh8y6PQTZNL_eUVpdZPum_eFH1i9UtLPGxSeFAlqVr6QMl_Q."
TIMEOUT: 20
SESSION_HEADERS :
    Host: "bard.google.com"
    X-Same-Domain: "1"
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
    Content-Type: "application/x-www-form-urlencoded;charset=UTF-8"
    Origin: "https://bard.google.com"
    Referer: "https://bard.google.com/"
